### PR TITLE
Memory pinning OutlineFuncs

### PR DESCRIPTION
**Pull request by varon**
This fixes two crashes with SharpFont:

1. A reference is kept to the delegates provided to OutlineFuncs. Without this, if GC runs, it will collect them, resulting in a runtime exception from the library.

2. Memory pinning is added to the delegates, preventing the GC from moving them and invalidating the function pointers we pass to FreeType.

This is a pretty critical fix, as without it, it's impossible to walk the outlines in a high-memory pressure environment.

### CODE REVIEW

**Comment by varon** [comment]
Also, as requested in #72, please can you update the NuGet package with these fixes.

**Comment by Robmaister** [comment]
This makes sense but I'd like the implementation to be slightly different.

 - `internal OutlineFuncsRec Record` doesn't ever set `shift` or `delta`, this is used in Outline.Decompose and will introduce unexpected behavior.
 - the disposable pattern isn't being followed properly. Face.cs is an example of a class that does. Essentially, create a private `Dispose(bool disposing)` and call it from both `Dispose()` the object finalizer `~OutlineFuncsRec()`. Include a "private bool disposed" and a property IsDisposed. The best concise example of this I could find online (most include a more expensive version meant for abstract/base classes) is the following: http://stackoverflow.com/questions/628752/why-call-disposefalse-in-the-destructor

I generally like to keep all data in rec up to date when values get set. Unless you're setting the functions more often than you are calling Outline.Decompose, you will be calling `Marshal` functions less often if you add `rec` back and marshal the delegates in the set block of the properties. This will add worst-case 32 bytes to the size but reduce the amount of marshaling and temporary memory allocations in the long run.

This is also not necessary for me to merge in the PR, but it would be nice if you could apply the same change to all of the other spots in SharpFont that use delegates/function pointers? RasterFuncs should essentially be the exact same changes. There are a few lesser used (or entirely unused) parts of SharpFont like Memory or RasterParams that are simply storing the delegates in the record class. I'd assume this doesn't function as expected (if it does, we should change OutlineFuncs back to that format) and should be updated to store IntPtrs and do the marshaling as well.

**Comment by varon** [comment]
@Robmaister Sorry about any delay. This should fix the incorrect IDisposable implementation, avoid the marshalling, and cover edge-cases with some defensive programming.

**Comment by varon** [comment]
Unfortunately I'm going to have to pass on fixing the other areas for now.

**Comment by varon** [comment]
@Robmaister Here's a quick reminder that this PR is still awaiting your feedback.

**Comment by Robmaister** [comment]
That's fine, I'll get around to a solution for the rest of the code base eventually. Looks good enough, I'll merge it in.

**Comment by varon** [comment]
Thanks a bunch for merging this. I really appreciate your work on this project.

If any of the other errors of this type end up affecting me, I'll be sure to submit a PR that fixes them as well.

**Comment by Robmaister** [comment]
Thanks! And definitely, I should be a little more responsive now that I'm done with the last of my college courses.

**Pull request merged**
