### PR TITLE
Library

### PR DESCRIPTION
**Pull request by drewkeller**
I managed to keep whitespace changes out of one of these but not the other. I'm not sure how to fix it at this point.
In FTBitmap, the only change is in line 455.... instead of multiplying each channel by a (R,G,B), only alpha is affected by i. So the original color is preserved throughout the palette values. Otherwise, it seems to be an odd sort of mask that goes from black to the original color and I couldn't figure out any kind of mask or blend scheme that would work with an arbitrary input color (this is easier to test, now that the example provides a way to change colors).

### CODE REVIEW

**Comment by Robmaister** [comment]
I believe this was originally a fix for #31. I can't exactly remember why I chose to premultiply, but I assume it was a fix that worked but didn't resolve the underlying issue. Are you seeing any of the same artifacts as that issue still? I'll also do some of my own testing.

Also is there any reason why Gray4 is still premultiplying? If not, can you change it back to just (R, G, B)?

**Comment by drewkeller** [comment]
Sorry for the long post....

I started adding an option to the example to select the pixel mode, but I'm not seeing how I would set the PixelMode of the SharpFont renderer. It looks like it's part of an internal structure the relevant FTBitmap property only has a getter? So I have not actually used the Gray4 or other color modes. (At one point, I was wanting to play with the OpenArgs but they are in a similar situation... internal access only).

Let me say first that I'm no graphics expert. I've arrived at the following after a certain amount of head scratching, fist shaking, and ... growling. I played around with various color blending functions in code and with image outputs in Gimp and finally found the simplest and (surely) the most performant method that got it to look right to me for all the color scenarios I tried was to let .Net graphcs do color blending via CompositingMode.SourceOver, gamma correction via the correct CompostingQuality setting (HighQuality or GammaCorrected), and use straight, linear alpha in the palette.

https://www.freetype.org/freetype2/docs/text-rendering-general.html says, "Text must be rendered with linear alpha blending and gamma correction..." Also read the paragraph following that, entitled "Background". The article also says that the stem darkening feature of the auto-hinter should be done when doing gamma correction (in other words, always...?). Does SharpFont have the stem darkening turned on or available somewhere?

https://www.freetype.org/freetype2/docs/reference/ft2-base_interface.html#FT_Render_Glyph also provides some relevant information (mostly a repeat of the gamma correction stuff). The alpha blending formula presented is for the OVER operator, which we can let .Net Graphics handle "auto-magically".

The "color fringing" or "dirt" issues can be most easily seen by rendering white (or light) text on a white background. It should be completely white, right?

**Comment by drewkeller** [comment]
So what is the plan with this? I see there are conflicts now with merging it.

**Comment by Robmaister** [comment]
Oh yes, there was one large change that added .NET Core/UWP/iOS/Android support and touched a few things in the Face class. This is a small change so I'll just manually merge it in a bit

**Comment by drewkeller** [comment]
I re-merged my project so I'll close this and open a new one.

**Pull request closed without merging**
