### PR TITLE
.NET Core 3 support.

### PR DESCRIPTION
**Pull request by PJB3005**
This multi targets the projects to net45;netcoreapp3.0.

To be straight honest, I didn't want to put in the effort to make this fully backwards compatible (keeping .NET 2 support or that PCL stuff) and I haven't bothered to update all the NuGet package stuff either.

I figured PRing this would be better than just keeping it in our fork permanently without mentioning it here, though.

### CODE REVIEW

**Comment by drjaydenm** [comment]
This would be great to have, we are using https://github.com/mellinoe/veldrid which fully supports .NET Core and would love to use this library for text rendering

**Comment by sunkin351** [comment]
Its 2022, with .NET 6 LTS available to the public. Has there not been any movement on this?

**Comment by PJB3005** [comment]
We're still using this version of SharpFont 3 years later no problem so :shrug:

**Comment by HinTak** [comment]
I think this should stay open, FWIW.

**Pull request closed without merging**
