### PR TITLE
If FreeType fails to open a font and assign a reference (such as for …

### PR DESCRIPTION
**Pull request by drewkeller**
…a bad font file), we should not try to release the non-existing reference when disposing the face.

On a related topic... perhaps Dispose() should not be throwing exceptions?
https://msdn.microsoft.com/en-us/library/bb386039.aspx

### CODE REVIEW

**Comment by HinTak** [comment]
I would have gone for a much simpler change: just ignore any error coming out of "FT.FT_Done_Face(base.Reference)", because, what exactly one can do about an error when one is just finished with using a type face? Nothing much at all.

I just grep'ed through both the freetype2 and freetype2-demo source trees. As I suggested above, the freetype developers themselves don't check the error code from FT_Done_Face() ever either :-).

**Comment by HinTak** [comment]
Just looked at the source code of FT_Done_Face() itself - it does not actually returns an error even if it fails to finish using a typeface. It only returns an error if the handle being passed in is invalid.

As such, the return code of FT_Done_Face() is meaningless - one should have checked the error code of FT_Open_Face() instead, for the purpose intended for this patch.

**Comment by HinTak** [comment]
I think the question is rather, why isn't FT_Open_Face() throwing an error when it fails to open a font?

**Comment by Robmaister** [comment]
I agree with @HinTak in this case, currently Library.OpenFace does check the return value of FT_Open_Face and throws a FreeTypeException, why isn't it being caught there?

On a side note, yes, we shouldn't be throwing an exception in Dispose. I believe this is done whenever there's a FT_Done_X call for the object. I will get around to it eventually, but if you'd like to open another PR for it, it'll probably get done quicker.

**Comment by drewkeller** [comment]
This is fairly simple to test.
1. Create an empty file and name it something like 'invalid.ttf'
2. Start the sample project 
3. Open the empty, invalid font file created in step 1 (File > Open font file). The program will attempt to open it and will actually throw an exception in the constructor, saying it's an invalid font file (no doubt about that :) The exception is caught and displayed in the status bar. The program keeps on running for now, BUT THE END IS NEAR!!! (sorry for the theatrics, but hey)
4. Do some other stuff to exercise the memory, like arrow up and down the valid fonts in the list.
5. Eventually... (whenever the .Net garbage collector feels like it), things will start disposing. When it attempts to dispose the invalid font file--CRASH.

I went through all of the Dispose() methods and eliminated the error checks for FT_Done_xx stuff. Doing so actually removed all the places that throw exceptions in Dispose().

**Comment by Robmaister** [comment]
Ah so perhaps the example project should be more resilient to exceptions when loading fonts. I'll still take the FT_Done_X changes. Thanks!

**Pull request merged**
