### PR TITLE
Squash warnings

### PR DESCRIPTION
**Pull request by drewkeller**
After all this, Visual Studio is displaying only 2 warnings, which are about obsolete FreeType functions being used. Much cleaner :)

### CODE REVIEW

**Comment by HinTak** [comment]
Hmm, this seems to bloat the source tree, without adding much real value. The 2nd patch seems is especially wrong in that regard. The first might be considered okay, except most of it doesn't add any new information which one cannot guess from the variable name itself.

If there is any quick single compiler switch to suppress those warnings, that might be considered preferable to bloating the source code?

**Comment by drewkeller** [comment]
Can you be more specific... in what way do you feel these changes "bloat" the source code?

Since the main purpose of this is a library, it would seem appropriate for public accessible elements to be documented. So I have a hard time arguing against the project settings in that regard (as chosen by Robmaister?). I agree that sometimes the information that can be conveyed in the comment is a bit trite, especially for enumeration values, but I don't think that lets us off the hook. Have a look at .Net's mind-numbing System.Drawing.Color enumeration, for example (https://msdn.microsoft.com/en-us/library/system.drawing.knowncolor%28v=vs.110%29.aspx?f=255&MSPPError=-2147217396).

The reorganization patch doesn't bloat source code (the only files with modifications are the project files, not source code); it is just reorganizing the existing files so the projects are separated, which may be more appropriate, anyway.

I have found there is definite value in having a clean slate so that real, actual warnings are plain to see instead of being nestled within hundreds of basically trivial warnings.

**Comment by Robmaister** [comment]
I agree that the documentation is more helpful than it is bloat. I originally enabled the missing documentation as warnings in the early days of this project to help me find places where I hadn't copy/pasted and formatted the original FreeType documentation. There were just a few places where their documentation was lacking and I put adding that documentation in on the backburner.

The changes are large enough to lag my browser, so I'm checking it out locally to see if everything is good.

**Comment by Robmaister** [comment]
Everything looks good besides one apparently missing file, ISfntTable.cs?

```
1>------ Build started: Project: SharpFont, Configuration: Release Any CPU ------
2>------ Build started: Project: SharpFont.iOS, Configuration: Release Any CPU ------
3>------ Build started: Project: SharpFont.Portable, Configuration: Release Any CPU ------
1>CSC : error CS2001: Source file 'D:\Projects\git\SharpFont\Source\SharpFontShared\TrueType\ISfntTable.cs' could not be found.
4>------ Build started: Project: Examples, Configuration: Release Any CPU ------
2>CSC : error CS2001: Source file 'D:\Projects\git\SharpFont\Source\SharpFontShared\TrueType\ISfntTable.cs' could not be found.
4>CSC : error CS0006: Metadata file 'D:\Projects\git\SharpFont\Binaries\SharpFont\Release\SharpFont.dll' could not be found
3>CSC : error CS2001: Source file 'D:\Projects\git\SharpFont\Source\SharpFontShared\TrueType\ISfntTable.cs' could not be found.
========== Build: 0 succeeded, 4 failed, 0 up-to-date, 0 skipped ==========
```

**Comment by drewkeller** [comment]
Sorry about that. Should be fixed now.

**Comment by Robmaister** [comment]
Great, thanks so much for all the changes!

**Comment by Robmaister** [comment]
Also I just cleaned up the obsolete warnings by marking the internal fields as also Obsolete in 2f5db2e1d

**Pull request merged**
