### PR TITLE
Implement Library.PropertySet on int type.

### PR DESCRIPTION
**Pull request by HinTak**
Specifically, this is for making
_lib.PropertySet("truetype", "interpreter-version", 35);
_lib.PropertySet("truetype", "interpreter-version", 40);
work.

https://github.com/Robmaister/SharpFont/issues/82

### CODE REVIEW

**Comment by Robmaister** [comment]
I believe there's a better way to get this working as a generic function. Have you tried pinning value with a GCHandle?

**Comment by HinTak** [comment]
I haven't... If you can get the generic/template function PropertySet&lt;T&gt; to work for value types that would be great :-). Tried PropertySet&lt;int&gt; and a few other things... PropertyGet does not work either, but I can live with just blindly setting it and trust that the value get set :-).

**Comment by HinTak** [comment]
I think the "out IntPtr" part of  PropertyGet is wrong - it might have worked without the "out" part, but it certainly won't work for &int , as "out ..." discards the input pointer and expect the routine to give the pointer a value. "out intPtr" is correct for reference types, returning a pre-existing pointer to a structure within freetype, but wrong for &int, where the routine expects a valid input pointer to a valid storage of 4 bytes to fill.

In any case, my addition works for me.

**Comment by Robmaister** [comment]
As mentioned in the issue, all overloads are now tested working.

**Comment by Robmaister** [comment]
I'll assume at this point that my generic implementation works just fine for you

**Comment by HinTak** [comment]
I assume so - however for even starting the testing, testing under dotnet2 runtime is a necessity. So I cannot look at SharpFont 4.0 until it regain dotnet2 runtime support. I might have to do it myself, or just keep using a forked 3.0 - the latter is easier, unfortunately.

**Comment by Robmaister** [comment]
Can you not just apply a LinqBridge reference/copy System.Core.dll in as discussed in #95 a while back? Everything up to .NET 3.5 will run on a 2.0 CLR given the correct libraries. I would be a whole lot more understanding if we were using something like async/await that was wholly incompatible with the 2.0 CLR, but LINQ is just a library with some syntax sugar with simple backwards compatibility solutions.

I view this in a similar way to how I provide builds of freetype6.dll. The last builds I did of freetype6.dll supported down to MSVC8 only because I managed to install VS 2005 on Windows 7. If it doesn't work in Windows 10 when I get around to setting up the same environment on my new machine, then I won't build them for versions that old. (In the same way I don't build against MSVC 7.1, 7, or 6). There are still instructions in the repo/elsewhere online on how to compile the library if you'd like to spin up an XP VM and compile against ancient VC++ runtimes.

**Comment by HinTak** [comment]
Whichever way of moving up to 4.x - backpacking to dotnet2 or grafting a 3rd party 3.5 on top - is extra work; and I am okay with a forked 3.X at the moment. 

Actually the reason I must support dotnet2 is this:
https://github.com/madewokherd/wine-mono/issues/29

So one way for me not to need dotnet2 is if that wine-mono bug gets fixed.

**Pull request closed without merging**
